export const FORMDATA_GET_REQUEST = 'FORMDATA_GET_REQUEST';
export const FORMDATA_GET_SUCCESS = 'FORMDATA_GET_SUCCESS';
export const FORMDATA_GET_ERROR = 'FORMDATA_GET_ERROR';

export const FORMDATA_SET_FORMDATA = 'FORMDATA_SET_FORMDATA';
export const FORMDATA_SET_QUERY = 'FORMDATA_SET_QUERY';
export const FORMDATA_SET_BET = 'FORMDATA_SET_BET';
